/*
 * generated by Xtext
 */
package com.github.jknack;

import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.osgi.framework.Bundle;

import com.github.jknack.generator.BuildConfigurationProvider;
import com.github.jknack.scoping.AntlrNameProvider;
import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Antlr4RuntimeModule extends com.github.jknack.AbstractAntlr4RuntimeModule {

  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.bind(Bundle.class).toInstance(Activator.bundle);
  }

  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return AntlrNameProvider.class;
  }

  public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
    return BuildConfigurationProvider.class;
  }
}
