/*
 * generated by Xtext
 */
package com.github.jknack.ui.contentassist

import com.github.jknack.ui.contentassist.AbstractAntlr4ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class Antlr4ProposalProvider extends AbstractAntlr4ProposalProvider {
}
